apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- ../../../../istio/oidc-authservice/base

configMapGenerator:
- name: oidc-authservice-parameters
  behavior: merge
  envs:
  - params.env
configurations:
- params.yaml