apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
- ../../../../dex-auth/dex-crds/overlays/istio

configMapGenerator:
- name: dex-parameters
  behavior: merge
  envs:
  - params.env